# Generated by Django 3.2.10 on 2023-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STOP', 'Stop')], default='STOP', max_length=5)),
                ('is_moving', models.BooleanField(default=False)),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
    ]
