# Generated by Django 3.2.10 on 2023-07-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_door_open',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField()),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elevators.elevator')),
            ],
        ),
    ]
